export const RESET_FETCH_LOGIN_DETAILS_WATCHER = 'RESET_FETCH_LOGIN_DETAILS_WATCHER';
export const FETCH_LOGIN_DETAILS_ACTION = 'FETCH_LOGIN_DETAILS_ACTION';
export const LOGIN_DETAILS_ACTION_SUCCESS = 'LOGIN_DETAILS_ACTION_SUCCESS';
export const LOGIN_DETAILS_ACTION_FAILURE = 'LOGIN_DETAILS_ACTION_FAILURE';



export const RESET_FETCH_SIGNUP_DETAILS_WATCHER = 'RESET_FETCH_SIGNUP_DETAILS_WATCHER';
export const FETCH_SIGNUP_DETAILS_WATCHER = 'FETCH_SIGNUP_DETAILS_WATCHER';
export const SET_SIGNUP_DETAILS_SUCCESS = 'SET_SIGNUP_DETAILS_SUCCESS';
export const SET_SIGNUP_DETAILS_FAILURE = 'SET_SIGNUP_DETAILS_FAILURE';

export const RESET_FETCH_CREATE_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_CREATE_PLAYLIST_DETAILS_WATCHER';
export const FETCH_CREATE_PLAYLIST_WATCHER = 'FETCH_CREATE_PLAYLIST_WATCHER';
export const SET_CREATE_PLAYLIST_SUCCESS = 'SET_CREATE_PLAYLIST_SUCCESS';
export const SET_CREATE_PLAYLIST_FAILURE = 'SET_CREATE_PLAYLIST_FAILURE';

export const RESET_FETCH_DELETE_SONG_DETAILS_WATCHER = 'RESET_FETCH_DELETE_SONG_DETAILS_WATCHER';
export const FETCH_DELETE_SONG_WATCHER = "FETCH_DELETE_SONG_WATCHER";
export const SET_DELETE_SONG_SUCCESS = "SET_DELETE_SONG_SUCCESS";
export const SET_DELETE_SONG_FAILURE = "SET_DELETE_SONG_FAILURE";

export const RESET_FETCH_VIEW_PLAYLISTS_DETAILS_WATCHER = 'RESET_FETCH_VIEW_PLAYLISTS_DETAILS_WATCHER';
export const FETCH_VIEW_PLAYLISTS_WATCHER = 'FETCH_VIEW_PLAYLISTS_WATCHER';
export const SET_VIEW_PLAYLISTS_SUCCESS = 'SET_VIEW_PLAYLISTS_SUCCESS';
export const SET_VIEW_PLAYLISTS_FAILURE = 'SET_VIEW_PLAYLISTS_FAILURE';

export const RESET_FETCH_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_PLAYLIST_DETAILS_WATCHER';
export const FETCH_PLAYLIST_DETAILS_WATCHER = 'FETCH_PLAYLIST_DETAILS_WATCHER';
export const SET_PLAYLIST_DETAILS_SUCCESS = 'SET_PLAYLIST_DETAILS_SUCCESS';
export const SET_PLAYLIST_DETAILS_FAILURE = 'SET_PLAYLIST_DETAILS_FAILURE';

export const RESET_FETCH_EDIT_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_EDIT_PLAYLIST_DETAILS_WATCHER';
export const FETCH_EDIT_PLAYLIST_WATCHER = "FETCH_EDIT_PLAYLIST_WATCHER";
export const SET_EDIT_PLAYLIST_SUCCESS = "SET_EDIT_PLAYLIST_SUCCESS";
export const SET_EDIT_PLAYLIST_FAILURE = "SET_EDIT_PLAYLIST_FAILURE";

export const RESET_FETCH_DELETE_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_DELETE_PLAYLIST_DETAILS_WATCHER';
export const FETCH_DELETE_PLAYLIST_WATCHER = "FETCH_DELETE_PLAYLIST_WATCHER";
export const SET_DELETE_PLAYLIST_SUCCESS = "SET_DELETE_PLAYLIST_SUCCESS";
export const SET_DELETE_PLAYLIST_FAILURE = "SET_DELETE_PLAYLIST_FAILURE";

export const RESET_FETCH_UPDATE_PASSWORD_DETAILS_WATCHER = 'RESET_FETCH_UPDATE_PASSWORD_DETAILS_WATCHER';
export const FETCH_UPDATE_PASSWORD_WATCHER = "FETCH_UPDATE_PASSWORD_WATCHER";
export const SET_UPDATE_PASSWORD_SUCCESS = "SET_UPDATE_PASSWORD_SUCCESS";
export const SET_UPDATE_PASSWORD_FAILURE = "SET_UPDATE_PASSWORD_FAILURE";

export const RESET_FETCH_UPDATE_USER_DETAILS_WATCHER = 'RESET_FETCH_UPDATE_USER_DETAILS_WATCHER';
export const FETCH_UPDATE_USER_WATCHER = "FETCH_UPDATE_USER_WATCHER";
export const SET_UPDATE_USER_SUCCESS = "SET_UPDATE_USER_SUCCESS";
export const SET_UPDATE_USER_FAILURE = "SET_UPDATE_USER_FAILURE";

export const RESET_FETCH_USERS_DETAILS_WATCHER = 'RESET_FETCH_USERS_DETAILS_WATCHER';
export const FETCH_USERS_DATA_ACTION = 'FETCH_USERS_DATA_ACTION';
export const USERS_ACTION_SUCCESS = 'USERS_ACTION_SUCCESS';
export const USERS_ACTION_FAILURE = 'USERS_ACTION_FAILURE';

export const RESET_FETCH_USER_DETAILS_WATCHER = 'RESET_FETCH_USER_DETAILS_WATCHER';
export const FETCH_USERS_DETAILS_ACTION = 'FETCH_USERS_DETAILS_ACTION';
export const SET_USER_DETAILS_SUCCESS = 'SET_USER_DETAILS_SUCCESS';
export const SET_USER_DETAILS_FAILURE = 'SET_USER_DETAILS_FAILURE';

export const RESET_FETCH_USER_ROLE_DETAILS_WATCHER = 'RESET_FETCH_USER_ROLE_DETAILS_WATCHER';
export const FETCH_USER_ROLE_DATA_ACTION = 'FETCH_USER_ROLE_DATA_ACTION';
export const SET_USER_ROLE_ACTION_SUCCESS = 'SET_USER_ROLE_ACTION_SUCCESS';
export const SET_USER_ROLE_ACTION_FAILURE = 'SET_USER_ROLE_ACTION_FAILURE';

export const RESET_FETCH_CREATE_SONG_DETAILS_WATCHER = 'RESET_FETCH_CREATE_SONG_DETAILS_WATCHER';
export const FETCH_CREATE_SONG_WATCHER = 'FETCH_CREATE_SONG_WATCHER';
export const SET_CREATE_SONG_SUCCESS = 'SET_CREATE_SONG_SUCCESS';
export const SET_CREATE_SONG_FAILURE = 'SET_CREATE_SONG_FAILURE';

export const RESET_FETCH_VIEW_SONGS_DETAILS_WATCHER = 'RESET_FETCH_VIEW_SONGS_DETAILS_WATCHER';
export const FETCH_VIEW_SONGS_WATCHER = 'FETCH_VIEW_SONGS_WATCHER';
export const SET_VIEW_SONGS_SUCCESS = 'SET_VIEW_SONGS_SUCCESS';
export const SET_VIEW_SONGS_FAILURE = 'SET_VIEW_SONGS_FAILURE';

export const RESET_FETCH_LIKE_SONG_DETAILS_WATCHER = 'RESET_FETCH_LIKE_SONG_DETAILS_WATCHER';
export const FETCH_LIKE_SONG_WATCHER = 'FETCH_LIKE_SONG_WATCHER';
export const SET_LIKE_SONG_SUCCESS = 'SET_LIKE_SONG_SUCCESS';
export const SET_LIKE_SONG_FAILURE = 'SET_LIKE_SONG_FAILURE';

export const RESET_FETCH_DISLIKE_SONG_DETAILS_WATCHER = 'RESET_FETCH_DISLIKE_SONG_DETAILS_WATCHER';
export const FETCH_DISLIKE_SONG_WATCHER = 'FETCH_DISLIKE_SONG_WATCHER';
export const SET_DISLIKE_SONG_SUCCESS = 'SET_DISLIKE_SONG_SUCCESS';
export const SET_DISLIKE_SONG_FAILURE = 'SET_DISLIKE_SONG_FAILURE';

export const RESET_FETCH_UPDATE_SONG_DETAILS_WATCHER = 'RESET_FETCH_UPDATE_SONG_DETAILS_WATCHER';
export const FETCH_UPDATE_SONG_WATCHER = "FETCH_UPDATE_SONG_WATCHER";
export const SET_UPDATE_SONG_SUCCESS = "SET_UPDATE_SONG_SUCCESS";
export const SET_UPDATE_SONG_FAILURE = "SET_UPDATE_SONG_FAILURE";

export const REPLACE_QUEUE_DETAILS_WATCHER = 'REPLACE_QUEUE_DETAILS_WATCHER';
export const CHANGE_CURRENT_SONG_WATCHER = "CHANGE_CURRENT_SONG_WATCHER";
export const SET_NEXT_SONG_WATCHER = "SET_NEXT_SONG_WATCHER";
export const SET_PREVIOUS_SONG_WATCHER = "SET_PREVIOUS_SONG_WATCHER";

export const RESET_FETCH_SONG_DETAILS_WATCHER = 'RESET_FETCH_SONG_DETAILS_WATCHER';
export const FETCH_SONG_DETAILS_WATCHER = 'FETCH_SONG_DETAILS_WATCHER';
export const SET_SONG_DETAILS_SUCCESS = 'SET_SONG_DETAILS_SUCCESS';
export const SET_SONG_DETAILS_FAILURE = 'SET_SONG_DETAILS_FAILURE';

export const FETCH_PLAYER_PLAY_PAUSE_DETAILS_WATCHER = 'FETCH_PLAYER_PLAY_PAUSE_DETAILS_WATCHER';

export const RESET_FETCH_LIKE_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_LIKE_PLAYLIST_DETAILS_WATCHER';
export const FETCH_LIKE_PLAYLIST_WATCHER = 'FETCH_LIKE_PLAYLIST_WATCHER';
export const SET_LIKE_PLAYLIST_SUCCESS = 'SET_LIKE_PLAYLIST_SUCCESS';
export const SET_LIKE_PLAYLIST_FAILURE = 'SET_LIKE_PLAYLIST_FAILURE';

export const RESET_FETCH_DISLIKE_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_DISLIKE_PLAYLIST_DETAILS_WATCHER';
export const FETCH_DISLIKE_PLAYLIST_WATCHER = 'FETCH_DISLIKE_PLAYLIST_WATCHER';
export const SET_DISLIKE_PLAYLIST_SUCCESS = 'SET_DISLIKE_PLAYLIST_SUCCESS';
export const SET_DISLIKE_PLAYLIST_FAILURE = 'SET_DISLIKE_PLAYLIST_FAILURE';

export const RESET_FETCH_ADD_TO_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_ADD_TO_PLAYLIST_DETAILS_WATCHER';
export const FETCH_ADD_TO_PLAYLIST_WATCHER = 'FETCH_ADD_TO_PLAYLIST_WATCHER';
export const SET_ADD_TO_PLAYLIST_SUCCESS = 'SET_ADD_TO_PLAYLIST_SUCCESS';
export const SET_ADD_TO_PLAYLIST_FAILURE = 'SET_ADD_TO_PLAYLIST_FAILURE';

export const RESET_FETCH_REMOVE_FROM_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_REMOVE_FROM_PLAYLIST_DETAILS_WATCHER';
export const FETCH_REMOVE_FROM_PLAYLIST_WATCHER = 'FETCH_REMOVE_FROM_PLAYLIST_WATCHER';
export const SET_REMOVE_FROM_PLAYLIST_SUCCESS = 'SET_REMOVE_FROM_PLAYLIST_SUCCESS';
export const SET_REMOVE_FROM_PLAYLIST_FAILURE = 'SET_REMOVE_FROM_PLAYLIST_FAILURE';

export const RESET_FETCH_SEARCH_SONG_DETAILS_WATCHER = 'RESET_FETCH_SEARCH_SONG_DETAILS_WATCHER';
export const FETCH_SEARCH_SONG_WATCHER = 'FETCH_SEARCH_SONG_WATCHER';
export const SET_SEARCH_SONG_SUCCESS = 'SET_SEARCH_SONG_SUCCESS';
export const SET_SEARCH_SONG_FAILURE = 'SET_SEARCH_SONG_FAILURE';

export const RESET_FETCH_SEARCH_PLAYLIST_DETAILS_WATCHER = 'RESET_FETCH_SEARCH_PLAYLIST_DETAILS_WATCHER';
export const FETCH_SEARCH_PLAYLIST_WATCHER = 'FETCH_SEARCH_PLAYLIST_WATCHER';
export const SET_SEARCH_PLAYLIST_SUCCESS = 'SET_SEARCH_PLAYLIST_SUCCESS';
export const SET_SEARCH_PLAYLIST_FAILURE = 'SET_SEARCH_PLAYLIST_FAILURE';

export const RESET_FETCH_SEARCH_ARTIST_DETAILS_WATCHER = 'RESET_FETCH_SEARCH_ARTIST_DETAILS_WATCHER';
export const FETCH_SEARCH_ARTIST_WATCHER = 'FETCH_SEARCH_ARTIST_WATCHER';
export const SET_SEARCH_ARTIST_SUCCESS = 'SET_SEARCH_ARTIST_SUCCESS';
export const SET_SEARCH_ARTIST_FAILURE = 'SET_SEARCH_ARTIST_FAILURE';

export const RESET_FETCH_ARTIST_ROLE_WATCHER = 'RESET_FETCH_ARTIST_ROLE_WATCHER';
export const FETCH_ARTIST_ROLE_WATCHER = 'FETCH_ARTIST_ROLE_WATCHER';
export const SET_ARTIST_ROLE_SUCCESS = 'SET_ARTIST_ROLE_SUCCESS';
export const SET_ARTIST_ROLE_FAILURE = 'SET_ARTIST_ROLE_FAILURE';

export const RESET_FETCH_ARTIST_DETAILS_WATCHER = 'RESET_FETCH_ARTIST_DETAILS_WATCHER';
export const FETCH_ARTIST_DETAILS_WATCHER = 'FETCH_ARTIST_DETAILS_WATCHER';
export const SET_ARTIST_DETAILS_SUCCESS = 'SET_ARTIST_DETAILS_SUCCESS';
export const SET_ARTIST_DETAILS_FAILURE = 'SET_ARTIST_DETAILS_FAILURE';

export const RESET_FETCH_FOLLOW_ARTIST_DETAILS_WATCHER = 'RESET_FETCH_FOLLOW_ARTIST_DETAILS_WATCHER';
export const FETCH_FOLLOW_ARTIST_DETAILS_WATCHER = 'FETCH_FOLLOW_ARTIST_DETAILS_WATCHER';
export const SET_FOLLOW_ARTIST_DETAILS_SUCCESS = 'SET_FOLLOW_ARTIST_DETAILS_SUCCESS';
export const SET_FOLLOW_ARTIST_DETAILS_FAILURE = 'SET_FOLLOW_ARTIST_DETAILS_FAILURE';

export const RESET_FETCH_UNFOLLOW_ARTIST_DETAILS_WATCHER = 'RESET_FETCH_UNFOLLOW_ARTIST_DETAILS_WATCHER';
export const FETCH_UNFOLLOW_ARTIST_DETAILS_WATCHER = 'FETCH_UNFOLLOW_ARTIST_DETAILS_WATCHER';
export const SET_UNFOLLOW_ARTIST_DETAILS_SUCCESS = 'SET_UNFOLLOW_ARTIST_DETAILS_SUCCESS';
export const SET_UNFOLLOW_ARTIST_DETAILS_FAILURE = 'SET_UNFOLLOW_ARTIST_DETAILS_FAILURE';

export const RESET_FETCH_FORGOT_PASSWORD_DETAILS_WATCHER = 'RESET_FETCH_FORGOT_PASSWORD_DETAILS_WATCHER';
export const FETCH_FORGOT_PASSWORD_DETAILS_WATCHER = 'FETCH_FORGOT_PASSWORD_DETAILS_WATCHER';
export const SET_FORGOT_PASSWORD_DETAILS_SUCCESS = 'SET_FORGOT_PASSWORD_DETAILS_SUCCESS';
export const SET_FORGOT_PASSWORD_DETAILS_FAILURE = 'SET_FORGOT_PASSWORD_DETAILS_FAILURE';

export const RESET_FETCH_VIEW_ARTIST_DETAILS_WATCHER = 'RESET_FETCH_VIEW_ARTIST_DETAILS_WATCHER';
export const FETCH_VIEW_ARTIST_DETAILS_WATCHER = 'FETCH_VIEW_ARTIST_DETAILS_WATCHER';
export const SET_VIEW_ARTIST_DETAILS_SUCCESS = 'SET_VIEW_ARTIST_DETAILS_SUCCESS';
export const SET_VIEW_ARTIST_DETAILS_FAILURE = 'SET_VIEW_ARTIST_DETAILS_FAILURE';

export const RESET_FETCH_RESET_PASSWORD_DETAILS_WATCHER = 'RESET_FETCH_RESET_PASSWORD_DETAILS_WATCHER';
export const FETCH_RESET_PASSWORD_DETAILS_WATCHER = 'FETCH_RESET_PASSWORD_DETAILS_WATCHER';
export const SET_RESET_PASSWORD_DETAILS_SUCCESS = 'SET_RESET_PASSWORD_DETAILS_SUCCESS';
export const SET_RESET_PASSWORD_DETAILS_FAILURE = 'SET_RESET_PASSWORD_DETAILS_FAILURE';

export const RESET_FETCH_USER_SUBSCRIPTION_DETAILS_WATCHER = 'RESET_FETCH_USER_SUBSCRIPTION_DETAILS_WATCHER';
export const FETCH_USER_SUBSCRIPTION_DETAILS_WATCHER = 'FETCH_USER_SUBSCRIPTION_DETAILS_WATCHER';
export const SET_USER_SUBSCRIPTION_DETAILS_SUCCESS = 'SET_USER_SUBSCRIPTION_DETAILS_SUCCESS';
export const SET_USER_SUBSCRIPTION_DETAILS_FAILURE = 'SET_USER_SUBSCRIPTION_DETAILS_FAILURE';

export const RESET_FETCH_CONFIRM_SUBSCRIPTION_DETAILS_WATCHER = 'RESET_FETCH_CONFIRM_SUBSCRIPTION_DETAILS_WATCHER';
export const FETCH_CONFIRM_SUBSCRIPTION_DETAILS_WATCHER = 'FETCH_CONFIRM_SUBSCRIPTION_DETAILS_WATCHER';
export const SET_CONFIRM_SUBSCRIPTION_DETAILS_SUCCESS = 'SET_CONFIRM_SUBSCRIPTION_DETAILS_SUCCESS';
export const SET_CONFIRM_SUBSCRIPTION_DETAILS_FAILURE = 'SET_CONFIRM_SUBSCRIPTION_DETAILS_FAILURE';

export const RESET_FETCH_INSTITUTE_DETAILS_WATCHER = 'RESET_FETCH_INSTITUTE_DETAILS_WATCHER';
export const FETCH_INSTITUTE_DETAILS_WATCHER = 'FETCH_INSTITUTE_DETAILS_WATCHER';
export const SET_INSTITUTE_DETAILS_SUCCESS = 'SET_INSTITUTE_DETAILS_SUCCESS';
export const SET_INSTITUTE_DETAILS_FAILURE = 'SET_INSTITUTE_DETAILS_FAILURE';

export const RESET_FETCH_COUNTRY_DETAILS_WATCHER = 'RESET_FETCH_COUNTRY_DETAILS_WATCHER';
export const FETCH_COUNTRY_DETAILS_WATCHER = 'FETCH_COUNTRY_DETAILS_WATCHER';
export const SET_COUNTRY_DETAILS_SUCCESS = 'SET_COUNTRY_DETAILS_SUCCESS';
export const SET_COUNTRY_DETAILS_FAILURE = 'SET_COUNTRY_DETAILS_FAILURE';

export const RESET_FETCH_CREATE_PLAN_DETAILS_WATCHER = 'RESET_FETCH_CREATE_PLAN_DETAILS_WATCHER';
export const FETCH_CREATE_PLAN_DETAILS_WATCHER = 'FETCH_CREATE_PLAN_DETAILS_WATCHER';
export const SET_CREATE_PLAN_DETAILS_SUCCESS = 'SET_CREATE_PLAN_DETAILS_SUCCESS';
export const SET_CREATE_PLAN_DETAILS_FAILURE = 'SET_CREATE_PLAN_DETAILS_FAILURE';

export const RESET_FETCH_VIEW_PLAN_DETAILS_WATCHER = 'RESET_FETCH_VIEW_PLAN_DETAILS_WATCHER';
export const FETCH_VIEW_PLAN_DETAILS_WATCHER = 'FETCH_VIEW_PLAN_DETAILS_WATCHER';
export const SET_VIEW_PLAN_DETAILS_SUCCESS = 'SET_VIEW_PLAN_DETAILS_SUCCESS';
export const SET_VIEW_PLAN_DETAILS_FAILURE = 'SET_VIEW_PLAN_DETAILS_FAILURE';

export const RESET_FETCH_EDIT_PLAN_DETAILS_WATCHER = 'RESET_FETCH_EDIT_PLAN_DETAILS_WATCHER';
export const FETCH_EDIT_PLAN_DETAILS_WATCHER = 'FETCH_EDIT_PLAN_DETAILS_WATCHER';
export const SET_EDIT_PLAN_DETAILS_SUCCESS = 'SET_EDIT_PLAN_DETAILS_SUCCESS';
export const SET_EDIT_PLAN_DETAILS_FAILURE = 'SET_EDIT_PLAN_DETAILS_FAILURE';

export const RESET_FETCH_PLAN_DETAILS_WATCHER = 'RESET_FETCH_PLAN_DETAILS_WATCHER';
export const FETCH_PLAN_DETAILS_WATCHER = 'FETCH_PLAN_DETAILS_WATCHER';
export const SET_PLAN_DETAILS_SUCCESS = 'SET_PLAN_DETAILS_SUCCESS';
export const SET_PLAN_DETAILS_FAILURE = 'SET_EDIT_PLAN_DETAILS_FAILURE';

export const RESET_FETCH_DELETE_PLAN_DETAILS_WATCHER = 'RESET_FETCH_DELETE_PLAN_DETAILS_WATCHER';
export const FETCH_DELETE_PLAN_DETAILS_WATCHER = 'FETCH_DELETE_PLAN_DETAILS_WATCHER';
export const SET_DELETE_PLAN_DETAILS_SUCCESS = 'SET_DELETE_PLAN_DETAILS_SUCCESS';
export const SET_DELETE_PLAN_DETAILS_FAILURE = 'SET_DELETE_PLAN_DETAILS_FAILURE';

export const RESET_FETCH_APPROVE_REQUEST_DETAILS_WATCHER = 'RESET_FETCH_APPROVE_REQUEST_DETAILS_WATCHER';
export const FETCH_APPROVE_REQUEST_DETAILS_WATCHER = 'FETCH_APPROVE_REQUEST_DETAILS_WATCHER';
export const SET_APPROVE_REQUEST_DETAILS_SUCCESS = 'SET_APPROVE_REQUEST_DETAILS_SUCCESS';
export const SET_APPROVE_REQUEST_DETAILS_FAILURE = 'SET_APPROVE_REQUEST_DETAILS_FAILURE';

export const RESET_FETCH_DISAPPROVE_REQUEST_DETAILS_WATCHER = 'RESET_FETCH_DISAPPROVE_REQUEST_DETAILS_WATCHER';
export const FETCH_DISAPPROVE_REQUEST_DETAILS_WATCHER = 'FETCH_DISAPPROVE_REQUEST_DETAILS_WATCHER';
export const SET_DISAPPROVE_REQUEST_DETAILS_SUCCESS = 'SET_DISAPPROVE_REQUEST_DETAILS_SUCCESS';
export const SET_DISAPPROVE_REQUEST_DETAILS_FAILURE = 'SET_DISAPPROVE_REQUEST_DETAILS_FAILURE';
