// export const BASE_URL = "http://localhost:5000";
export const BASE_URL = "https://music-player-pu5z.onrender.com";

export const API_URL = {
    LOGIN: "/login",
    SIGNUP: "/signup",
        
    DELETE_SONG: "/deleteSong",
    CREATE_PLAYLIST: "/createPlaylist",
    VIEW_PLAYLIST: "/playlists",
    GET_PLAYLIST: "/playlist",
    UPDATE_PLAYLIST: "/updatePlaylist",
    DELETE_PLAYLIST: "/deletePlaylist",
    UPDATE_PASSWORD: "/updatePassword",
    UPDATE_USER_INFO: "/updateMe",
    USER_DETAILS: "/user",
    USER_ROLE_DETAILS: "/listeners",
    CREATE_SONG: "/songs",
    VIEW_SONGS: "/getSongs",
    LIKE_SONG: "/likes/add",
    DISLIKE_SONG: "/likes/remove",
    UPDATE_SONG: "/updateSong",
    LIKE_PLAYLIST: "/playlist/likes/add",
    DISLIKE_PLAYLIST: "/playlist/likes/remove",
    ADD_TO_PLAYLIST: "/addToPlaylist",
    REMOVE_FROM_PLAYLIST: "/removeFromPlaylist",
    SEARCH_SONG: "/song",
    SEARCH_ARTIST: "/artist",
    SEARCH_PLAYLIST: "/playlist",
    BECOME_ARTIST: "/becomeArtist",
    FOLLOW_ARTIST: "/follow",
    UNFOLLOW_ARTIST: "/unfollow",
    FORGOT_PASSWORD: "/forgotPassword",
    VIEW_ARTIST: "/artists",
    RESET_PASSWORD: "/resetPassword",
    USER_SUBSCRIPTION: "/student",
    INSTITUTE: "/istitute",
    CONFIRM_SUBSCRIPTION: "/confirm-subscription",
    CREATE_PLAN: "/createPlan",
    VIEW_PLAN: "/plan",
    EDIT_PLAN: "/editPlan",
    GET_PLAN: "/getPlan",
    DELETE_PLAN: "/deletePlan",
    APPROVE_REQUEST: "/approve",
    DISAPPROVE_REQUEST: "/disapprove",
}